name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Build
      run: npm run build-site

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.2
      with:
        access_token: ${{ secrets.ACCESS_TOKEN }}
        branch: site-deploy
        folder: site
